# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Thu Aug 24 18:00:40 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(605, 360)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.flashMCUGroup = QtGui.QGroupBox(self.centralWidget)
        self.flashMCUGroup.setGeometry(QtCore.QRect(10, 90, 580, 110))
        self.flashMCUGroup.setObjectName("flashMCUGroup")
        self.startAddrLabel = QtGui.QLabel(self.flashMCUGroup)
        self.startAddrLabel.setGeometry(QtCore.QRect(10, 70, 120, 20))
        self.startAddrLabel.setObjectName("startAddrLabel")
        self.statusLabel = QtGui.QLabel(self.centralWidget)
        self.statusLabel.setGeometry(QtCore.QRect(20, 250, 450, 15))
        self.statusLabel.setObjectName("statusLabel")
        self.resetMCUCheckBox = QtGui.QCheckBox(self.flashMCUGroup)
        self.resetMCUCheckBox.setGeometry(QtCore.QRect(260, 70, 140, 20))
        self.resetMCUCheckBox.setObjectName("resetMCUCheckBox")
        self.pathLineEdit = QtGui.QLineEdit(self.flashMCUGroup)
        self.pathLineEdit.setGeometry(QtCore.QRect(90, 30, 400, 20))
        self.pathLineEdit.setObjectName("pathLineEdit")
        self.flashButton = QtGui.QPushButton(self.flashMCUGroup)
        self.flashButton.setGeometry(QtCore.QRect(500, 70, 75, 23))
        self.flashButton.setObjectName("flashButton")
        self.browseButton = QtGui.QPushButton(self.flashMCUGroup)
        self.browseButton.setGeometry(QtCore.QRect(500, 30, 75, 23))
        self.browseButton.setObjectName("browseButton")
        # self.verifyUploadCheckBox = QtGui.QCheckBox(self.flashMCUGroup)
        # self.verifyUploadCheckBox.setGeometry(QtCore.QRect(410, 70, 91, 20))
        # self.verifyUploadCheckBox.setObjectName("verifyUploadCheckBox")
        self.downloadFileLabel = QtGui.QLabel(self.flashMCUGroup)
        self.downloadFileLabel.setGeometry(QtCore.QRect(10, 30, 70, 20))
        self.downloadFileLabel.setObjectName("downloadFileLabel")
        self.startAddrLineEdit = QtGui.QLineEdit(self.flashMCUGroup)
        self.startAddrLineEdit.setGeometry(QtCore.QRect(140, 70, 60, 20))
        self.startAddrLineEdit.setObjectName("startAddrLineEdit")

        self.connetGroup = QtGui.QGroupBox(self.centralWidget)
        self.connetGroup.setGeometry(QtCore.QRect(10, 20, 580, 40))
        self.connetGroup.setTitle("")
        self.connetGroup.setObjectName("connetGroup")
        self.adapterLabel = QtGui.QLabel(self.connetGroup)
        self.adapterLabel.setGeometry(QtCore.QRect(10, 10, 50, 20))
        self.adapterLabel.setObjectName("adapterLabel")
        self.connectButton = QtGui.QPushButton(self.connetGroup)
        self.connectButton.setGeometry(QtCore.QRect(55, 10, 75, 23))
        self.connectButton.setObjectName("connectButton")
        self.jlinkDeviceLabel = QtGui.QLabel(self.connetGroup)
        self.jlinkDeviceLabel.setGeometry(QtCore.QRect(135, 10, 85, 20))
        self.jlinkDeviceLabel.setObjectName("jlinkDeviceLabel")      
        self.jlinkDeviceCombo = QtGui.QComboBox(self.connetGroup)
        self.jlinkDeviceCombo.setGeometry(QtCore.QRect(220, 10, 85, 20))
        self.jlinkDeviceCombo.setObjectName("jlinkDeviceCombo")
        self.debugIFLabel = QtGui.QLabel(self.connetGroup)
        self.debugIFLabel.setGeometry(QtCore.QRect(315, 10, 50, 20))
        self.debugIFLabel.setObjectName("debugIFLabel")      
        self.debugIFCombo = QtGui.QComboBox(self.connetGroup)
        self.debugIFCombo.setGeometry(QtCore.QRect(365, 10, 50, 20))
        self.debugIFCombo.setObjectName("debugIFCombo") 
        self.deviceLabel = QtGui.QLabel(self.connetGroup)
        self.deviceLabel.setGeometry(QtCore.QRect(425, 10, 150, 20))
        self.deviceLabel.setObjectName("deviceLabel")
        MainWindow.setCentralWidget(self.centralWidget)
        self.mainToolBar = QtGui.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Programmer Tool", None, QtGui.QApplication.UnicodeUTF8))
        self.flashMCUGroup.setTitle(QtGui.QApplication.translate("MainWindow", "Flash MCU", None, QtGui.QApplication.UnicodeUTF8))
        self.startAddrLabel.setText(QtGui.QApplication.translate("MainWindow", "Flash start address(hex):", None, QtGui.QApplication.UnicodeUTF8))
        self.statusLabel.setText(QtGui.QApplication.translate("MainWindow", "Ready", None, QtGui.QApplication.UnicodeUTF8))
        self.resetMCUCheckBox.setText(QtGui.QApplication.translate("MainWindow", "Reset MCU after flashing", None, QtGui.QApplication.UnicodeUTF8))
        self.flashButton.setText(QtGui.QApplication.translate("MainWindow", "Flash", None, QtGui.QApplication.UnicodeUTF8))
        self.browseButton.setText(QtGui.QApplication.translate("MainWindow", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        # self.verifyUploadCheckBox.setText(QtGui.QApplication.translate("MainWindow", "Verify upload", None, QtGui.QApplication.UnicodeUTF8))
        self.downloadFileLabel.setText(QtGui.QApplication.translate("MainWindow", "Download File", None, QtGui.QApplication.UnicodeUTF8))
        self.adapterLabel.setText(QtGui.QApplication.translate("MainWindow", "Adapter", None, QtGui.QApplication.UnicodeUTF8))
        self.connectButton.setText(QtGui.QApplication.translate("MainWindow", "Connect", None, QtGui.QApplication.UnicodeUTF8))
        self.jlinkDeviceLabel.setText(QtGui.QApplication.translate("MainWindow", "J-Link Device S/N", None, QtGui.QApplication.UnicodeUTF8))
        self.debugIFLabel.setText(QtGui.QApplication.translate("MainWindow", "Debug IF", None, QtGui.QApplication.UnicodeUTF8))
        self.deviceLabel.setText(QtGui.QApplication.translate("MainWindow", "Device:", None, QtGui.QApplication.UnicodeUTF8))

