# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Wed Sep 06 14:45:15 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(605, 360)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.flashMCUGroup = QtGui.QGroupBox(self.centralWidget)
        self.flashMCUGroup.setGeometry(QtCore.QRect(10, 90, 581, 111))
        self.flashMCUGroup.setObjectName("flashMCUGroup")
        self.startAddrLabel = QtGui.QLabel(self.flashMCUGroup)
        self.startAddrLabel.setGeometry(QtCore.QRect(10, 70, 101, 20))
        self.startAddrLabel.setObjectName("startAddrLabel")
        self.resetMCUCheckBox = QtGui.QCheckBox(self.flashMCUGroup)
        self.resetMCUCheckBox.setGeometry(QtCore.QRect(260, 70, 141, 20))
        self.resetMCUCheckBox.setObjectName("resetMCUCheckBox")
        self.pathLineEdit = QtGui.QLineEdit(self.flashMCUGroup)
        self.pathLineEdit.setGeometry(QtCore.QRect(90, 30, 401, 21))
        self.pathLineEdit.setObjectName("pathLineEdit")
        self.flashButton = QtGui.QPushButton(self.flashMCUGroup)
        self.flashButton.setGeometry(QtCore.QRect(500, 70, 75, 23))
        self.flashButton.setObjectName("flashButton")
        self.browseButton = QtGui.QPushButton(self.flashMCUGroup)
        self.browseButton.setGeometry(QtCore.QRect(500, 30, 75, 23))
        self.browseButton.setObjectName("browseButton")
        self.verifyUploadCheckBox = QtGui.QCheckBox(self.flashMCUGroup)
        self.verifyUploadCheckBox.setGeometry(QtCore.QRect(410, 70, 91, 20))
        self.verifyUploadCheckBox.setObjectName("verifyUploadCheckBox")
        self.downloadFileLabel = QtGui.QLabel(self.flashMCUGroup)
        self.downloadFileLabel.setGeometry(QtCore.QRect(10, 30, 71, 20))
        self.downloadFileLabel.setObjectName("downloadFileLabel")
        self.startAddrLineEdit = QtGui.QLineEdit(self.flashMCUGroup)
        self.startAddrLineEdit.setGeometry(QtCore.QRect(110, 70, 141, 21))
        self.startAddrLineEdit.setObjectName("startAddrLineEdit")
        self.connetGroup = QtGui.QGroupBox(self.centralWidget)
        self.connetGroup.setGeometry(QtCore.QRect(10, 20, 581, 41))
        self.connetGroup.setTitle("")
        self.connetGroup.setObjectName("connetGroup")
        self.jlinkDeviceLabel = QtGui.QLabel(self.connetGroup)
        self.jlinkDeviceLabel.setGeometry(QtCore.QRect(140, 10, 71, 21))
        self.jlinkDeviceLabel.setObjectName("jlinkDeviceLabel")
        self.adapterLabel = QtGui.QLabel(self.connetGroup)
        self.adapterLabel.setGeometry(QtCore.QRect(10, 10, 51, 20))
        self.adapterLabel.setObjectName("adapterLabel")
        self.connectButton = QtGui.QPushButton(self.connetGroup)
        self.connectButton.setGeometry(QtCore.QRect(60, 10, 75, 23))
        self.connectButton.setObjectName("connectButton")
        self.jlinkDeviceCombo = QtGui.QComboBox(self.connetGroup)
        self.jlinkDeviceCombo.setGeometry(QtCore.QRect(210, 10, 161, 22))
        self.jlinkDeviceCombo.setObjectName("jlinkDeviceCombo")
        self.label = QtGui.QLabel(self.connetGroup)
        self.label.setGeometry(QtCore.QRect(380, 10, 191, 20))
        self.label.setObjectName("label")
        self.label_2 = QtGui.QLabel(self.centralWidget)
        self.label_2.setGeometry(QtCore.QRect(20, 230, 47, 13))
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralWidget)
        self.mainToolBar = QtGui.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Programmer Tool", None, QtGui.QApplication.UnicodeUTF8))
        self.flashMCUGroup.setTitle(QtGui.QApplication.translate("MainWindow", "Flash MCU", None, QtGui.QApplication.UnicodeUTF8))
        self.startAddrLabel.setText(QtGui.QApplication.translate("MainWindow", "Flash start address:", None, QtGui.QApplication.UnicodeUTF8))
        self.resetMCUCheckBox.setText(QtGui.QApplication.translate("MainWindow", "Reset MCU after flashing", None, QtGui.QApplication.UnicodeUTF8))
        self.flashButton.setText(QtGui.QApplication.translate("MainWindow", "Flash", None, QtGui.QApplication.UnicodeUTF8))
        self.browseButton.setText(QtGui.QApplication.translate("MainWindow", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.verifyUploadCheckBox.setText(QtGui.QApplication.translate("MainWindow", "Verify upload", None, QtGui.QApplication.UnicodeUTF8))
        self.downloadFileLabel.setText(QtGui.QApplication.translate("MainWindow", "Download File", None, QtGui.QApplication.UnicodeUTF8))
        self.jlinkDeviceLabel.setText(QtGui.QApplication.translate("MainWindow", "J-Link Device", None, QtGui.QApplication.UnicodeUTF8))
        self.adapterLabel.setText(QtGui.QApplication.translate("MainWindow", "Adapter", None, QtGui.QApplication.UnicodeUTF8))
        self.connectButton.setText(QtGui.QApplication.translate("MainWindow", "Connect", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Device:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))

